sudo: true
dist: trusty
language: scala
jdk:
- openjdk11
scala:
- 2.12.10
stages:
- test
- name: release
  if: tag =~ ^v
- name: snapshot
  if: "(NOT tag IS present) AND (type = push)"
jobs:
  include:
  - stage: test
    script: sbt "project examples" clean coverage test && sbt test && sbt "project
      examples" coverageReport coveralls
  - stage: release
    script: openssl aes-256-cbc -K $encrypted_03ddc50c8705_key -iv $encrypted_03ddc50c8705_iv
      -in ci/secring.asc.enc -out ci/secring.asc -d && gpg --import ci/secring.asc
      && sbt publishSigned testkit/publishSigned sonatypeBundleRelease
  - stage: snapshot
    script: sbt publish testkit/publish
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
env:
  global:
  - secure: c+1zbvfSDi8Rdwehsq91CsBMqPsOQDJC5Y6+tBGyjQToHnsmO5iEvdcXfjFMh01Hz8P2TVVZoH2+NRVxkAnlLyWZMaJ6ex6FqfaCcbnYIbRQzOQIuQDN2sttm95NMhj8WBrO583DmqQyaPzBQ2pg6tDRLoDK/KBBCeCJcptag5eM6j/iSX1yRnaascyOJy++6afCPp//PN3a1Aow81E67IWgPINq0xwm4rPOvtt5VKtQBfYAfmQSViM6bvQw3eiFy/M/oanD0rb5gQWaHYVtWEJ5fOQmbGw+GKQloUshb7BQWzSYg5j9mAt95IFcl1MQXTe9oOt/gKsX4smDopFqb2ovFkLl9ZbaRu80tJ90CmLWZq/LE63Rtdqeil4Sd2xkxJyfNZMcdDuZZDleCm8qcVId/hBMiji4/Hm3DOO6JuUqhVwRo0Msr/PKV3/FxArWA2oRk7L9WvXaRI43kApB+uKZK4B25SOeSDKwUCs3lCB2uGerMeCcmkjKOeTbY37b9a4nlrrEbGLefslBnAS1z5J9VKuxAMdTv8A45p0apcNfRBMqAYEzEFHWFpwj5e5iAelYe++BPnOHzqE7ziA7EvtVAyAamyNQaluMfm//lAiWbLa7ZS1M9bclKFv8xjRhYNu2o9xexvXwG6nsh9taYJ25GBKI3ZoW/EsAQb/9sIU=
  - secure: Dbnj5qZHGWCOBNTj5K/V7m49+zGiITo0r9xOgDx9fgxGk4QhS5zDccUf69kH+mQEMrJi8Io0acnIP+hrF2Mi/TgbzIkJDi9kewQdLbMSuJy0GutTFZYPFUvQdM5ibfZ4g3ASr3/R2gCefSZ7mtxhOCzeeZhej+6UAtDQQvBDykF+PJDVxbYArTtnGWbtUqZKjKW6WH97oec2tJMQQ61HKJ8x8XeTIF7BDnEmVKvBXn3opM5R8K3mo5kIdqzEvb2yKtmOunGh6B6Ek2wHi3pLasJC1Tu3RaOP1nvF2/OXNuB0LbR74W9jldeFhqYQH513MhmYUv+ss41rT4zBAqIYZ9HmiNK9yASFNHa6uAzRg05IL0U4L1ILzfgG4xh7QsQBJ3PVwd//SW1lhEY3dqGbGrjTutrVXLMVy7O6EIqsfgZX9VS2IkFFW1LXg+JdX+NDxrKkRQSR1Lh4d5QamDSjUt7Gk5kZhKZYlRcvLs6GBd3G0oQaL5eI7uc0av0GHp44MHgpH9G3WE2lXqaoz5mSEaz+srh0CP8Zswj/Lpd39AdVcnUYzshQgBNn5UVRpp8EJNHc/yDtOx2vTMuNHxYOcrSRj9bPT7QsC9KJbWb5wNQoC5BepH+cjq0iph/8/vGxM/mf62qQDZtKTZfYO29aqqWpbzClImZLt6wxEJ8ESTs=
  - secure: c1jkJW37ciy6GpCanTa2COm8eK42I7ISkxiHCJKWFdPRcviMPLPPAjQ43NwGssinTMZ1bhnuRYP4OHAsPEmJoxi+FQUuv1c8vPSEOr4TdtPEMgWmyUFHxWOaIdXzgk+udci68QWtvMEtOcKk5lY7AJln6ZxtBfH9o2TIfZXZn3xCGNd+6tCPj1uqlrS/Ne5XdpcaIfHD7hdYKxYikj8hI3zEZroD5R5QPrPB6M8XqR3E0dA70ERdCAVim+1uiJGlUp6l6yg2cBvhgeaU71dH1wcXOKJuzLRK5K2acDhjkcheQoeLjatASGhplp7pZIbfF+UN4Vl4K0drBuS/H3QGi0F/HipDTTyEEtI32kh0i7IgNfwx1iyzKeipB0/An4TPh58y/9hRxNUA+IQ7+W3mwfm9NLaeVMRjOelLpPUDeWJmTkL9QmlQ2zGDx+B4C3KvTApnGHxRKIdeY7k/KnpM9J+GTy9L5Yf0l1hFdvPbe8B0nwA38M2PafAP8vqBWGa8ke7k1I5Yn83Yup4SbT7+b/SE9qqZzhx1RXtFFsBPR0vsEoGL/pMBXu4nh+zL3xO3O5APcYMGe6Ur/1tDtl9HhgZGaheIlp+EWCOlSM9Pq4fYoJiV2T8to6zgIyCSxcV+IjW+ySmRLRJRoyF5y2CblKdaPfOcI0vpMDFQGlnM8IQ=
